yamlApplicationConfig:
  kafka:
    clusters:
      - name: cp-confluent
        bootstrapServers:  kafka.confluent.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
